name: geogami-morphology

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.12
  - osmnx=2.1.1
  - geopandas
  - shapely
  - networkx
  - pandas
  - numpy
  - scipy
  - matplotlib
  - pyproj
  - pytest
